export const text = {
  en: {
    welcome: "Welcome!",
    signupUserTaken: "Sorry, username is already taken!",
    signupNameTaken: "Sorry, name is already taken!",
    signupError: "Sorry, there was an error somehow. Try again?",
    signupShortPW: "Password must be at least 6 characters long!",
    signupUnmatchedPW: "Passwords do not match!",
    signupNewUser: "Create New User",
    name: "Name:",
    username: "Username:",
    password: "Password:",
    confirmPassword: "Confirm Password:",
    signupCreate: "Create User",
  },
  
  simplifiedCN: {
    welcome: "欢迎！",
    signupUserTaken: "不好意思，用户名已被占用！",
    signupNameTaken: "不好意思， 名字已被占用！",
    signupError: "不好意思，登录失败。再试一试？",
    signupShortPW: "密码必须至少6个字符!",
    signupUnmatchedPW: "密码不匹配!",
    signupNewUser: "创建新用户",
    name: "名字:",
    username: "用户名:",
    password: "密码:",
    confirmPassword: "确认密码:",
    signupCreate: "创建用户",
  },
  traditionaldCN: {
    welcome: "歡迎！",
    signupUserTaken: "不好意思，用戶名已被佔用！",
    signupNameTaken: "不好意思， 名字已被佔用！ ",
    signupError: "不好意思，登錄失敗。再試一試?",
    signupShortPW: "密碼必須至少6個字符! ",
    signupUnmatchedPW: "密碼不匹配!",
    signupNewUser: "創建新用戶",
    name: "名字:",
    username: "用戶名:",
    password: "密碼:",
    confirmPassword: "確認密碼:",
    signupCreate: "創建用戶",
  },
};